# TOML v1.0
# Variables will ask to input

zpvars = [
  { name = 'cli', type = 'confirm', message = 'Do you need a cli way?', default = false },
  { name = 'sync', type = 'list', choices = [ { name = 'Asynchronous', value = 'async ' }, { name = 'Synchronous', value = '' } ], message = 'Is your extension function synchronous or asynchronous?', default = 'async ' },
]
